web:
  build: .
  command: sh -c 'npm install; npm start '
  ports:
    - '3000:3000'
  
  volumes:
    - /home/mona/Escritorio/bbdd nosql/star-wars-master/api:/api
  
  links:
    - 'db:redis-sw'

db:
  image: redis
  ports:
    - '6379:6379'

